/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carinsurance;
import java.util.*;

public class PolicyException extends Exception{
    private static int policyID;
    
    //PolicyException constructor throws a PolicyException
    public PolicyException(int policyID){
        this.policyID = generateID();
    }
    
    //Get new generated ID
    public static int getNewPolicyID(){
        return policyID;
    }
    
    //Generate ID follow the ID pattern: 3xxxxxx
    public int generateID(){
        int newPolicyID = (int) ((Math.random() * ((3999999 - 3000000)+1))+3000000);
        return newPolicyID;
    }
    
    //Creates an error message
    public String toString(){
        return "The Policy ID is no valid and a new ID: (" + policyID + ") is generated by admin and assigned for the Policy";
    }
}
